name: CI/CD Pipeline - Weather Prediction App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t weather-app .

      # Step 4: Run container (smoke test)
      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 weather-app
          sleep 10
          docker ps

      # Step 5: Stop container
      - name: Stop Docker container
        run: |
          docker stop $(docker ps -q)